DELETE http://localhost:3000/api/users/660aa027166712ae89ddd513
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QzIiwiaWQiOiI2NjBhYTAyNzE2NjcxMmFlODlkZGQ1MTMiLCJpYXQiOjE3MTE5NzI0NTl9.Q0eT-QhmY-EoFjc--sN28XFJhu4dYO_Lbu07PJXLGo0